version: '3.8'

services:
  ec2-client:
    build:
      context: .
    privileged: true  # Needed for vsock access
    network_mode: "host"
    volumes:
      - /var/run/vsock:/var/run/vsock
    environment:
      - ENCLAVE_CID=3  # Default CID, can be overridden
      - ENCLAVE_PORT=5000
    command: ["-cid", "${ENCLAVE_CID}", "-port", "${ENCLAVE_PORT}"]

networks:
  default:
    driver: bridge